name: Build Mini WebView APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: "33.0.2"

      - run: chmod +x ./gradlew
      - run: ./gradlew assembleDebug

      # Debugging: cek hasil build, biar ketahuan path APK
      - run: ls -R . | grep .apk || true

      - uses: actions/upload-artifact@v4
        with:
          name: mini-webview-apk
          path: '**/debug/*.apk'
